name: Publish docs

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: textbook/git-checkout-submodule-action@master
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm i -D typescript
      - run: npm run docs
