name: Publish docs

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  generate-documentation:
    runs-on: ubuntu-latest
    env:
      SURGE_LOGIN: ${{secrets.SURGE_LOGIN}}
      SURGE_TOKEN: ${{secrets.SURGE_TOKEN}}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm i --no-save typescript typedoc
      - run: npm run docs
